image: docker

stages:
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

test:
  stage: test
  script:
    - docker-compose -f compose/test/docker-compose.test.yml build
    - docker-compose -f compose/test/docker-compose.test.yml run unbfeelings-test python3 manage.py test
