version: '3'
services:
  dev:
    image: unbfeelings/unbfeelings:dev
    command: python3 manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    volumes:
      - .:/home/developer/software
    ports:
      - "8000:8000"
