version: '3'
services:
  # Server
  nginx-prod:
    image: nginx:latest
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/production.conf
      - ../unbfeelings/staticfiles:/usr/share/nginx/html
    ports:
      - "8001:8000"
    restart: unless-stopped
    depends_on:
      - unbfeelings-prod
      - unbfeelings-front

  # Production enviroment
  unbfeelings-prod:
    image: unbfeelings/api:latest
    restart: unless-stopped
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres
    restart: unless-stopped

  # Frontend production enviroment
  unbfeelings-front:
    image: unbfeelings/front:latest
    restart: unless-stopped
