version: '3'
services:
  unbfeelings-dev:
    build: .
    volumes:
      - ../../:/home/developer/software
    command: bash -c "chmod +x compose/dev/dev.sh && ./compose/dev/dev.sh"
    ports:
      - "8000:8000"
    image: unbfeelings-dev
    container_name: unbfeelings-dev
